name: 'Upstream Sync'
description: 'Sync your repository with an upstream repository'

author: 'DevMatrixs'

inputs:
  GIT_NAME:
    description: 'Git user name (default: GitHub Actions)'
    required: false
    default: 'GitHub Actions'
  GIT_EMAIL:
    description: 'Git user email (default: actions@github.com)'
    required: false
    default: 'actions@github.com'
  UPSTREAM_REPO:
    description: 'The name of the upstream repository (required).'
    required: true
  TARGET_BRANCH:
    description: 'The target branch in your repository (default: main)'
    required: false
    default: 'main'
  UPSTREAM_BRANCH:
    description: 'The upstream branch to merge from (default: main)'
    required: false
    default: 'main'
  FORCE_PUSH:
    description: 'If true, forces push to the target branch'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GIT_NAME: ${{ inputs.GIT_NAME }}
    INPUT_GIT_EMAIL: ${{ inputs.GIT_EMAIL }}
    INPUT_UPSTREAM_REPO: ${{ inputs.UPSTREAM_REPO }}
    INPUT_TARGET_BRANCH: ${{ inputs.TARGET_BRANCH }}
    INPUT_UPSTREAM_BRANCH: ${{ inputs.UPSTREAM_BRANCH }}
    INPUT_FORCE_PUSH: ${{ inputs.FORCE_PUSH }}
  entrypoint: "/home/ci/entrypoint.sh"
