name: Sync Fork with Upstream

description: 'Fork repository ko upstream repository ke saath sync karo.'

inputs:
  github_token:
    description: 'Authentication ke liye GitHub token'
    required: true
  fork_repo:
    description: 'Fork repository ka URL (jaise, username/repo)'
    required: true
  upstream_repo:
    description: 'Upstream repository ka URL (jaise, username/repo)'
    required: true
  branch:
    description: 'Sync karne wali branch (default: main)'
    required: false
    default: 'main'
  custom_user_name:
    description: 'Custom Git user name (optional)'
    required: false
  custom_user_email:
    description: 'Custom Git user email (optional)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh ${{ inputs.github_token }} ${{ inputs.fork_repo }} ${{ inputs.upstream_repo }} ${{ inputs.branch }} ${{ inputs.custom_user_name }} ${{ inputs.custom_user_email }}'
