name: Upstream Sync

description: Sync changes from the source branch in upstream to the target branch.

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  upstream_repo:
    description: 'Upstream repository (owner/repo)'
    required: true
  source_branch:
    description: 'Source branch in the upstream repository'
    required: true
  target_branch:
    description: 'Target branch to merge into'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.source_branch }}
    - ${{ inputs.target_branch }}

branding:
  icon: 'git-merge'
  color: 'blue'
