name: "Upstream Sync and Push"
description: "This action syncs with the upstream repository and pushes changes"

inputs:
  github_token:
    description: 'GitHub Token for authentication (if not provided, defaults to GitHub token)'
    required: false
  upstream_repo:
    description: 'Name of the upstream repository (e.g., username/repo-name)'
    required: true
  source_branch:
    description: 'Branch from the upstream repository to sync from'
    required: true
  target_branch:
    description: 'Branch in the forked repo to push changes to'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.github_token }}'  # If provided
    - '${{ secrets.GITHUB_TOKEN }}'  # Fallback to GitHub Actions token
    - '${{ inputs.upstream_repo }}'
    - '${{ inputs.source_branch }}'
    - '${{ inputs.target_branch }}'
