name: 'Upstream Sync'
description: 'Sync your repository with an upstream repository'

author: 'Your Name <your-email@example.com>'

inputs:
  GIT_NAME:
    description: 'Git user name (default: GitHub Actions)'
    required: false
    default: 'GitHub Actions'
  GIT_EMAIL:
    description: 'Git user email (default: actions@github.com)'
    required: false
    default: 'actions@github.com'
  UPSTREBM_REPO:
    description: 'The name of the upstream repository (required).'
    required: true
  TARGET_BRANCH:
    description: 'The target branch in your repository (default: main)'
    required: false
    default: 'main'
  UPSTREAM_BRANCH:
    description: 'The upstream branch to merge from (default: main)'
    required: false
    default: 'main'
  FORCE_PUSH:
    description: 'If true, forces push to the target branch'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: "git-merge"
  color: "blue"
