name: Sync Fork with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync fork with upstream
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fork_repo: "your-fork-repo"
          upstream_repo: "j-hc/revanced-magisk-module"
          branch: "main"
          custom_user_name: ${{ secrets.GIT_USERNAME }}
          custom_user_email: ${{ secrets.GIT_EMAIL }}
