name: Upstream Sync and Push

on:
  workflow_dispatch:

jobs:
  sync_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GitHub Token
      uses: actions/github-script@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Upstream Sync Action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_repo: 'username/repository'
        source_branch: 'main'
        target_branch: 'main'
        script: './entrypoint.sh'
