name: Sync with Upstream

on:
  workflow_dispatch:  # Manual trigger ke liye

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repository ko checkout karna
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Docker action ko run karna (same repository mein)
      - name: Sync with upstream repository
        uses: ./  # Ye current directory se action ko use karega
        with:
          GIT_NAME: 'GitHub Actions'  # Agar aapko default user name chahiye
          GIT_EMAIL: 'actions@github.com'  # Agar aapko default email chahiye
          UPSTREAM_REPO: 'upstream/repository-name'  # Upstream repository ka naam
          TARGET_BRANCH: 'main'  # Target branch (default 'main')
          UPSTREAM_BRANCH: 'main'  # Upstream branch (default 'main')
          FORCE_PUSH: 'false'  # Force push ko false rakhein
