name: Sync Upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync upstream
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repo: 'owner/repo'
          source_branch: 'source-branch'
          target_branch: 'target-branch'
