name: Sync Upstream Changes

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
        default: ${{ secrets.GITHUB_TOKEN }}
      upstream_repo:
        description: 'Upstream Repository (owner/repo)'
        required: true
      source_branch:
        description: 'Source Branch'
        required: true
      target_branch:
        description: 'Target Branch'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Upstream Sync
        uses: ./  # Use the current directory to run the action
        with:
          github_token: ${{ github.token }}
          upstream_repo: ${{ github.event.inputs.upstream_repo }}
          source_branch: ${{ github.event.inputs.source_branch }}
          target_branch: ${{ github.event.inputs.target_branch }}
