name: Sync with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Sync with upstream repository
        uses: ./  
        with:
          GIT_NAME: 'GitHub Actions'
          GIT_EMAIL: 'actions@github.com'
          UPSTREAM_REPO: 'j-hc/revanced-magisk-module'
          TARGET_BRANCH: 'main'
          UPSTREAM_BRANCH: 'main'
          FORCE_PUSH: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
