name: Upstream Sync and Push

on:
  push:
    branches:
      - main

jobs:
  sync_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GitHub Token
      uses: actions/setup-git@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Upstream Sync Action
      uses: ./  # Assuming this action is in the root directory of your repo
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_repo: 'username/repository'
        source_branch: 'main'
        target_branch: 'main'
