name: Upstream Sync and Push

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

jobs:
  sync_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Upstream Sync Action
      uses: ./  # Assuming this action is in the root directory of your repo
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        upstream_repo: 'j-hc/revanced-magisk-module'
        source_branch: 'main'
        target_branch: 'main'
