name: Upstream Sync Workflow

on:
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Upstream Sync Action
        uses: ./ 
        with:
          GIT_NAME: '${{ secrets.GIT_NAME }}'
          GIT_EMAIL: '${{ secrets.GIT_EMAIL }}'
          UPSTREAM_REPO: 'upstream-owner/repository-name'
          TARGET_BRANCH: 'main'
          UPSTREAM_BRANCH: 'main'
          FORCE_PUSH: 'false'
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
